apiVersion: v1
appVersion: 1.12.5
description: Open source, multi-cloud continuous delivery platform for releasing software
  changes with high velocity and confidence.
home: http://spinnaker.io/
icon: https://pbs.twimg.com/profile_images/669205226994319362/O7OjwPrh_400x400.png
maintainers:
- email: viglesias@google.com
  name: viglesiasce
- email: lwander@google.com
  name: lwander
- email: hello@dwardu.com
  name: dwardu89
- email: username.taken@gmail.com
  name: paulczar
name: spinnaker
sources:
- https://github.com/spinnaker
- https://github.com/viglesiasce/images
version: 1.8.0
