apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketmqcluster-configmap
  namespace: default
data:
  broker.conf.sample: |-
    #所属集群名字
    brokerClusterName=rocketmqcluster
    #broker名字，注意此处不同的配置文件填写的不一样  例如：在a.properties 文件中写 broker-a  在b.properties 文件中写 broker-b
    brokerName=broker-a
    #0 表示 Master，>0 表示 Slave
    brokerId=0
    #nameServer地址，分号分割
    namesrvAddr=rocketmq-nameserver-0.rocketmq-nameserver:9876;rocketmq-nameserver-1.rocketmq-nameserver:9876
    #在发送消息时，自动创建服务器不存在的topic，默认创建的队列数
    defaultTopicQueueNums=10
    #是否允许 Broker 自动创建Topic，建议线下开启，线上关闭
    autoCreateTopicEnable=false
    #是否允许 Broker 自动创建订阅组，建议线下开启，线上关闭
    autoCreateSubscriptionGroup=true
    #Broker 对外服务的监听端口
    listenPort=10911
    #删除文件时间点，默认凌晨 4点
    deleteWhen=04
    #文件保留时间，默认 48 小时
    fileReservedTime=72
    #commitLog每个文件的大小默认1G
    mapedFileSizeCommitLog=1073741824
    #ConsumeQueue每个文件默认存30W条，根据业务情况调整
    mapedFileSizeConsumeQueue=300000
    #destroyMapedFileIntervalForcibly=120000
    #redeleteHangedFileInterval=120000
    #检测物理文件磁盘空间
    diskMaxUsedSpaceRatio=80
    #存储路径
    storePathRootDir=/opt/rocketmq/store
    #commitLog 存储路径
    #storePathCommitLog=/rocketmqdata/rocketmq/store/commitlog
    #消费队列存储路径存储路径
    #storePathConsumeQueue=/rocketmqdata/rocketmq/store/consumequeue
    #消息索引存储路径
    #storePathIndex=/rocketmqdata/rocketmq/store/index
    #checkpoint 文件存储路径
    #storeCheckpoint=/rocketmqdata/rocketmq/store/checkpoint
    #abort 文件存储路径
    #abortFile=/rocketmqdata/rocketmq/store/abort
    #限制的消息大小
    maxMessageSize=4194304
    #flushCommitLogLeastPages=4
    #flushConsumeQueueLeastPages=2
    #flushCommitLogThoroughInterval=10000
    #flushConsumeQueueThoroughInterval=60000
    #Broker 的角色
    #- ASYNC_MASTER 异步复制Master
    #- SYNC_MASTER 同步双写Master
    #- SLAVE
    brokerRole=ASYNC_MASTER
    #刷盘方式
    #- ASYNC_FLUSH 异步刷盘
    #- SYNC_FLUSH 同步刷盘
    flushDiskType=ASYNC_FLUSH
    #checkTransactionMessageEnable=false
    #发消息线程池数量
    sendMessageThreadPoolNums=128
    #拉消息线程池数量
    pullMessageThreadPoolNums=128
