apiVersion: v1
kind: Pod
metadata:
  name: fabric-init-pod
  labels:
    app: fabric-init
spec:
  containers:
    - name: fabric-init
      image: registry.cn-shenzhen.aliyuncs.com/cos-solution/fabric-tools:x86_64-1.0.0
      imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
      env:
        - name: FABRIC_CHANNEL
          value: {{ .Values.fabricChannel | quote }}
      command: ["/var/hyperledger/production/config/fabric-init.sh"]
      volumeMounts:
        - name: fabric-network-root
          mountPath: /var/hyperledger/production
      readinessProbe:
        exec:
          command:
          - ls
          - /var/hyperledger/production/INIT-COMPLETED
        initialDelaySeconds: 5
        periodSeconds: 5
  initContainers:
    - name: check-generator
      image: registry.cn-shenzhen.aliyuncs.com/cos-solution/fabric-tools:x86_64-1.0.0
      imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
      command: ['sh', '-c', 'sleep 5; until [ -f /var/hyperledger/production/GENERATION-COMPLETED ]; do echo waiting for fabric-network-generator; sleep 5; done; sleep 5;']
      volumeMounts:
        - name: fabric-network-root
          mountPath: /var/hyperledger/production
          readOnly: true
  volumes:
    - name: fabric-network-root
      hostPath:
        path: /data/fabric/{{ $.Values.fabricNetwork }}
        # Below type field is necessary to avoid auto creation of dir if not present during init container check
        type: Directory