apiVersion: v1
appVersion: 2.8.1
description: Elegantly enables a Tiller per namespace in RBAC-enabled clusters
home: https://github.com/kubernetes/charts/tree/master/stable/magic-namespace
maintainers:
- email: kent.rancourt@microsoft.com
  name: krancour
name: magic-namespace
version: 0.2.0
