apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
  namespace: default
value: 1000000
globalDefault: false
#preemptionPolicy: Never
description: "This priority class should be used for XYZ service pods only."
