---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-blackbox-exporter/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.311
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: prometheus-blackbox-exporter
    version: 2.2.311
    expose: "true"
    group: io.fabric8.devops.apps
    kind: catalog
  name: catalog-prometheus-blackbox-exporter
data:
  catalog-prometheus-blackbox-exporter.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-blackbox-exporter/src/main/fabric8/icon.png"
        fabric8.io/git-branch: "release-v2.2.311"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "prometheus-blackbox-exporter"
        version: "2.2.311"
        expose: "true"
        group: "io.fabric8.devops.apps"
      name: "prometheus-blackbox-exporter"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9115"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-blackbox-exporter/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          expose: "true"
          provider: "fabric8"
          project: "prometheus-blackbox-exporter"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "blackbox-exporter"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - name: "http"
          port: 80
          protocol: "TCP"
          targetPort: 9115
        selector:
          project: "prometheus-blackbox-exporter"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "ConfigMap"
      metadata:
        annotations: {}
        finalizers: []
        labels:
          provider: "fabric8"
          project: "prometheus-blackbox-exporter"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "blackbox-exporter"
        ownerReferences: []
      data:
        config.yml: "modules:\n  http_2xx:\n    prober: http\n    timeout: 5s\n    http:\n\
          \      valid_status_codes: []  # Defaults to 2xx\n      method: GET\n      no_follow_redirects:\
          \ false\n      fail_if_ssl: false\n      fail_if_not_ssl: false"
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-blackbox-exporter/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=prometheus-blackbox-exporter&var-version=2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "prometheus-blackbox-exporter"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "prometheus-blackbox-expo"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            project: "prometheus-blackbox-exporter"
            provider: "fabric8"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-blackbox-exporter/src/main/fabric8/icon.png"
              fabric8.io/git-branch: "release-v2.2.311"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=prometheus-blackbox-exporter&var-version=2.2.311"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "prometheus-blackbox-exporter"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env: []
              image: "prom/blackbox-exporter:master"
              livenessProbe:
                httpGet:
                  httpHeaders: []
                  port: "http"
                initialDelaySeconds: 1
              name: "blackbox-exporter"
              ports:
              - containerPort: 9115
                name: "http"
              readinessProbe:
                httpGet:
                  httpHeaders: []
                  port: "http"
                initialDelaySeconds: 1
              volumeMounts:
              - mountPath: "/etc/blackbox_exporter"
                name: "config-volume"
            imagePullSecrets: []
            nodeSelector: {}
            volumes:
            - configMap:
                items: []
                name: "blackbox-exporter"
              name: "config-volume"
    parameters: []
