---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.311
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: gogs
    repository: gogs
    scm: git
    version: 2.2.311
    expose: "true"
    group: io.fabric8.devops.apps
    kind: catalog
  name: catalog-gogs
data:
  catalog-gogs.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png"
        fabric8.io/git-branch: "release-v2.2.311"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "gogs"
        repository: "gogs"
        scm: "git"
        version: "2.2.311"
        expose: "true"
        group: "io.fabric8.devops.apps"
      name: "gogs"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "Secret"
      metadata:
        annotations: {}
        finalizers: []
        labels:
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
          project: "gogs"
          repository: "gogs"
          scm: "git"
          version: "2.2.311"
        name: "default-gogs-git"
        namespace: "user-secrets-source-admin"
        ownerReferences: []
      data:
        password: "UmVkSGF0JDE="
        username: "Z29nc2FkbWlu"
      stringData: {}
    - apiVersion: "v1"
      kind: "ServiceAccount"
      metadata:
        annotations:
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png"
        finalizers: []
        labels:
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
          project: "gogs"
          version: "2.2.311"
        name: "gogs"
        ownerReferences: []
      imagePullSecrets: []
      secrets: []
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/app-menu: "development"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "gogs"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
          expose: "true"
        name: "gogs"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - port: 80
          protocol: "TCP"
          targetPort: 3000
        selector:
          project: "gogs"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "gogs"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
          expose: "true"
        name: "gogs-ssh"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - port: 22
          protocol: "TCP"
          targetPort: 2222
        selector:
          project: "gogs"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "PersistentVolumeClaim"
      metadata:
        annotations:
        finalizers: []
        labels:
          provider: "fabric8"
          project: "gogs"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "gogs-data"
        ownerReferences: []
      spec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          limits: {}
          requests:
            storage: "100Mi"
    - apiVersion: "v1"
      kind: "ConfigMap"
      metadata:
        annotations: {}
        finalizers: []
        labels:
          provider: "fabric8"
          project: "gogs"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "fabric8-git-app-secrets"
        namespace: "user-secrets-source-admin"
        ownerReferences: []
      data:
        gogs: "default-git-gogs"
    - apiVersion: "v1"
      kind: "ConfigMap"
      metadata:
        annotations:
          fabric8.gogs/summary: "[Gogs](http://gogs/) - A self-hosted Git service written\
            \ in Go"
          description: "Gogs is a self-hosted Git service written in Go.\n\nMore details\
            \ on the <a href=\"http://gogs.io/\" target=\"gogs\">Gogs home page</a>.\n"
          fabric8.gogs/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png"
          expose.config.fabric8.io/url-key: "gogs-server--root-url"
          expose.config.fabric8.io/oauth-authorize-url-key: "oauth-authorize-uri"
          fabric8.io/json-schema: "{\n  \"type\" : \"object\",\n  \"properties\" : {\n\
            \    \"GOGS_SERVER__ROOT_URL\" : {\n      \"type\" : \"string\",\n      \"\
            description\" : \"The root URL for the gogs server\"\n    },\n    \"DOMAIN\"\
            \ : {\n      \"type\" : \"string\",\n      \"description\" : \"The domain\
            \ name applications are installed on\",\n      \"default\" : \"vagrant.f8\"\
            \n    },\n    \"ADMIN_USER_EMAIL\" : {\n      \"type\" : \"string\",\n   \
            \   \"description\" : \"The email address of the admin user on Gogs\",\n \
            \     \"default\" : \"gogsadmin@fabric8.local\"\n    },\n    \"ADMIN_USER_PASSWORD\"\
            \ : {\n      \"type\" : \"string\",\n      \"description\" : \"The password\
            \ to login to Gogs\",\n      \"default\" : \"RedHat$1\"\n    },\n    \"GOGS_SERVER__PROTOCOL\"\
            \ : {\n      \"type\" : \"string\",\n      \"description\" : \"The protocol\
            \ for gogs to use; either http or https\",\n      \"default\" : \"http\"\n\
            \    },\n    \"GOGS_OAUTH_OPENSHIFT__ENABLED\" : {\n      \"type\" : \"string\"\
            ,\n      \"default\" : \"true\"\n    },\n    \"ADMIN_USER_CREATE\" : {\n \
            \     \"type\" : \"string\",\n      \"description\" : \"Should we create an\
            \ admin user on startup\",\n      \"default\" : \"true\"\n    },\n    \"GOGS_OAUTH_OPENSHIFT__TOKEN_URL\"\
            \ : {\n      \"type\" : \"string\"\n    },\n    \"GOGS_OAUTH_OPENSHIFT__SCOPES\"\
            \ : {\n      \"type\" : \"string\"\n    },\n    \"GOGS_OAUTH_OPENSHIFT__AUTH_URL\"\
            \ : {\n      \"type\" : \"string\"\n    },\n    \"GOGS_WEBHOOK__TASK_INTERVAL\"\
            \ : {\n      \"type\" : \"string\",\n      \"default\" : \"true\"\n    },\n\
            \    \"GOGS_WEBHOOK__SKIP_TLS_VERIFY\" : {\n      \"type\" : \"string\",\n\
            \      \"default\" : \"true\"\n    },\n    \"GOGS_SERVER__DOMAIN\" : {\n \
            \     \"type\" : \"string\",\n      \"description\" : \"The gogs server name\"\
            ,\n      \"default\" : \"gogs.vagrant.f8\"\n    },\n    \"ADMIN_USER_NAME\"\
            \ : {\n      \"type\" : \"string\",\n      \"description\" : \"The user name\
            \ to login to Gogs\",\n      \"default\" : \"gogsadmin\"\n    },\n    \"GOGS_OAUTH__ENABLED\"\
            \ : {\n      \"type\" : \"string\",\n      \"default\" : \"true\"\n    },\n\
            \    \"GOGS_OAUTH_TWITTER__ENABLED\" : {\n      \"type\" : \"string\",\n \
            \     \"default\" : \"false\"\n    },\n    \"KUBERNETES_ADMIN_USER\" : {\n\
            \      \"type\" : \"string\",\n      \"description\" : \"The default Kubernetes\
            \ admin user\",\n      \"default\" : \"admin\"\n    },\n    \"GOGS_OAUTH_OPENSHIFT__CLIENT_ID\"\
            \ : {\n      \"type\" : \"string\",\n      \"default\" : \"gogs\"\n    }\n\
            \  }\n}"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "gogs"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "gogs"
        ownerReferences: []
      data:
        admin-user-create: "true"
        admin-user-email: "gogsadmin@fabric8.local"
        admin-user-name: "gogsadmin"
        admin-user-password: "RedHat$1"
        gogs-oauth--enabled: "true"
        gogs-oauth-openshift--auth-url: ""
        gogs-oauth-openshift--client-id: "gogs"
        gogs-oauth-openshift--enabled: "true"
        gogs-oauth-openshift--scopes: ""
        gogs-oauth-openshift--token-url: ""
        gogs-oauth-twitter--enabled: "false"
        gogs-server--root-url: ""
        gogs-webhook--skip-tls-verify: "true"
        gogs-webhook--task-interval: "true"
        kubernetes-admin-user: "admin"
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          configmap.fabric8.io/update-on-change: "gogs"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/git-branch: "release-v2.2.311"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=gogs&var-version=2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "gogs"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "gogs"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            provider: "fabric8"
            project: "gogs"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png"
              fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
              configmap.fabric8.io/update-on-change: "gogs"
              fabric8.io/git-branch: "release-v2.2.311"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=gogs&var-version=2.2.311"
              pod.alpha.kubernetes.io/init-containers: "[{\"image\":\"busybox\",\"imagePullPolicy\"\
                :\"IfNotPresent\",\"name\":\"init\",\"command\":[\"chmod\",\"777\",\"\
                /app/gogs/data\"],\"volumeMounts\":[{\"mountPath\":\"/app/gogs/data\"\
                ,\"name\":\"gogs-data\"}]}]"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "gogs"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "GOGS_SERVER__ROOT_URL"
                valueFrom:
                  configMapKeyRef:
                    key: "gogs-server--root-url"
                    name: "gogs"
              - name: "ADMIN_USER_EMAIL"
                valueFrom:
                  configMapKeyRef:
                    key: "admin-user-email"
                    name: "gogs"
              - name: "ADMIN_USER_PASSWORD"
                valueFrom:
                  configMapKeyRef:
                    key: "admin-user-password"
                    name: "gogs"
              - name: "ADMIN_USER_CREATE"
                value: "true"
              - name: "GOGS_WEBHOOK__TASK_INTERVAL"
                value: "true"
              - name: "GOGS_WEBHOOK__SKIP_TLS_VERIFY"
                value: "true"
              - name: "ADMIN_USER_NAME"
                valueFrom:
                  configMapKeyRef:
                    key: "admin-user-name"
                    name: "gogs"
              - name: "KUBERNETES_ADMIN_USER"
                valueFrom:
                  configMapKeyRef:
                    key: "kubernetes-admin-user"
                    name: "gogs"
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              image: "fabric8/gogs:v0.9.97"
              imagePullPolicy: "IfNotPresent"
              name: "gogs"
              ports:
              - containerPort: 2222
                name: "ssh"
              - containerPort: 3000
                name: "http"
              resources:
                limits:
                  cpu: "0"
                  memory: "0"
                requests:
                  cpu: "0"
                  memory: "0"
              volumeMounts:
              - mountPath: "/app/gogs/data"
                name: "gogs-data"
            imagePullSecrets: []
            nodeSelector: {}
            serviceAccountName: "gogs"
            volumes:
            - name: "gogs-data"
              persistentVolumeClaim:
                claimName: "gogs-data"
    parameters: []
