---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 0b90360981bed67ebde7b71cc6a96d34cca3dcc6
    fabric8.io/iconUrl: img/icons/activemq.svg
    fabric8.io/git-branch: release-v2.2.168
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: message-broker
    version: 2.2.168
    group: io.fabric8.ipaas.apps
    kind: catalog
  name: catalog-message-broker
data:
  catalog-message-broker.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "0b90360981bed67ebde7b71cc6a96d34cca3dcc6"
        fabric8.io/iconUrl: "img/icons/activemq.svg"
        fabric8.io/git-branch: "release-v2.2.168"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "message-broker"
        version: "2.2.168"
        group: "io.fabric8.ipaas.apps"
      name: "message-broker"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/iconUrl: "img/icons/activemq.svg"
          fabric8.io/git-commit: "0b90360981bed67ebde7b71cc6a96d34cca3dcc6"
          fabric8.io/git-branch: "release-v2.2.168"
        finalizers: []
        labels:
          provider: "fabric8"
          group: "io.fabric8.ipaas.apps"
          project: "message-broker"
          version: "2.2.168"
        name: "message-broker"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - port: 61616
          protocol: "TCP"
          targetPort: 61616
        selector:
          provider: "fabric8"
          group: "io.fabric8.ipaas.apps"
          project: "message-broker"
    - apiVersion: "v1"
      kind: "PersistentVolumeClaim"
      metadata:
        annotations:
        finalizers: []
        labels:
          provider: "fabric8"
          project: "message-broker"
          version: "2.2.168"
          group: "io.fabric8.ipaas.apps"
        name: "message-broker"
        ownerReferences: []
      spec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          limits: {}
          requests:
            storage: "100Mi"
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/iconUrl: "img/icons/activemq.svg"
          fabric8.io/git-commit: "0b90360981bed67ebde7b71cc6a96d34cca3dcc6"
          fabric8.io/git-branch: "release-v2.2.168"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=message-broker&var-version=2.2.168"
        finalizers: []
        labels:
          provider: "fabric8"
          group: "io.fabric8.ipaas.apps"
          project: "message-broker"
          version: "2.2.168"
        name: "message-broker"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            provider: "fabric8"
            group: "io.fabric8.ipaas.apps"
            project: "message-broker"
        template:
          metadata:
            annotations:
              fabric8.io/iconUrl: "img/icons/activemq.svg"
              fabric8.io/git-commit: "0b90360981bed67ebde7b71cc6a96d34cca3dcc6"
              fabric8.io/git-branch: "release-v2.2.168"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=message-broker&var-version=2.2.168"
              pod.alpha.kubernetes.io/init-containers: "[{\"image\":\"busybox\",\"imagePullPolicy\"\
                :\"IfNotPresent\",\"name\":\"init\",\"command\":[\"chmod\",\"777\",\"\
                /data/message-broker/\"],\"volumeMounts\":[{\"mountPath\":\"/data/message-broker/\"\
                ,\"name\":\"message-broker\"}]}]"
            finalizers: []
            labels:
              provider: "fabric8"
              group: "io.fabric8.ipaas.apps"
              project: "message-broker"
              version: "2.2.168"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              image: "fabric8/message-broker:2.2.168"
              imagePullPolicy: "IfNotPresent"
              name: "message-broker"
              ports:
              - containerPort: 61616
                name: "amq"
              - containerPort: 8778
                name: "jolokia"
              resources:
                limits:
                  cpu: "0"
                  memory: "0"
                requests:
                  cpu: "0"
                  memory: "0"
              securityContext:
                privileged: false
              volumeMounts:
              - mountPath: "/data/message-broker/"
                name: "message-broker"
            imagePullSecrets: []
            nodeSelector: {}
            volumes:
            - name: "message-broker"
              persistentVolumeClaim:
                claimName: "message-broker"
    parameters: []
