---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gitlab/src/main/fabric8/icon.svg
    fabric8.io/git-branch: release-v2.2.311
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: gitlab
    version: 2.2.311
    expose: "true"
    group: io.fabric8.devops.apps
    kind: catalog
  name: catalog-gitlab
data:
  catalog-gitlab.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gitlab/src/main/fabric8/icon.svg"
        fabric8.io/git-branch: "release-v2.2.311"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "gitlab"
        version: "2.2.311"
        expose: "true"
        group: "io.fabric8.devops.apps"
      name: "gitlab"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/app-menu: "development"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gitlab/src/main/fabric8/icon.svg"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          project: "gitlab"
          provider: "fabric8"
          expose: "true"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "gitlab"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - port: 80
          protocol: "TCP"
          targetPort: 80
        selector:
          project: "gitlab"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gitlab/src/main/fabric8/icon.svg"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          project: "gitlab"
          provider: "fabric8"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "gitlab-ssh"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - port: 22
          protocol: "TCP"
          targetPort: 22
        selector:
          project: "gitlab"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "ConfigMap"
      metadata:
        annotations:
          fabric8.gitlab/summary: "[Gitlab](http://gitlab.com/) - A self-hosted Git service"
          description: "Gitlab is a self-hosted Git service      \n\nMore details on the\
            \ <a href=\"http://gitlab.com/\" target=\"gitlab\">Gitlab home page</a>.\n"
          fabric8.io/json-schema: "{\n  \"type\" : \"object\",\n  \"properties\" : {\n\
            \    \"JENKINS_GITLAB_USER\" : {\n      \"type\" : \"string\",\n      \"description\"\
            \ : \"The user name for Jenkins to login to Gitlab\",\n      \"default\" :\
            \ \"jenkins\"\n    },\n    \"JENKINS_GITLAB_PASSWORD\" : {\n      \"type\"\
            \ : \"string\",\n      \"description\" : \"The password for Jenkins to login\
            \ to Gitlab\",\n      \"default\" : \"RedHat$1\"\n    },\n    \"GITLAB_URL\"\
            \ : {\n      \"type\" : \"string\",\n      \"description\" : \"The GitLab\
            \ server URL\",\n      \"default\" : \"gitlab.vagrant.f8\"\n    },\n    \"\
            JENKINS_GITLAB_EMAIL\" : {\n      \"type\" : \"string\",\n      \"description\"\
            \ : \"The email address of the Jenkins user on Gitlab\",\n      \"default\"\
            \ : \"gitlab@fabric8.local\"\n    }\n  }\n}"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "gitlab"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "gitlab"
        ownerReferences: []
      data:
        jenkins-gitlab-password: "RedHat$1"
        gitlab-url: "gitlab.vagrant.f8"
        jenkins-gitlab-user: "jenkins"
        jenkins-gitlab-email: "gitlab@fabric8.local"
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gitlab/src/main/fabric8/icon.svg"
          fabric8.io/git-branch: "release-v2.2.311"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=gitlab&var-version=2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "gitlab"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "gitlab"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            provider: "fabric8"
            project: "gitlab"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gitlab/src/main/fabric8/icon.svg"
              fabric8.io/git-branch: "release-v2.2.311"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=gitlab&var-version=2.2.311"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "gitlab"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              image: "gitlab/gitlab-ce"
              imagePullPolicy: "IfNotPresent"
              name: "gitlab"
              ports:
              - containerPort: 22
                name: "ssh"
              - containerPort: 80
                name: "http"
              - containerPort: 443
                name: "https"
              resources:
                limits:
                  cpu: "0"
                  memory: "0"
                requests:
                  cpu: "0"
                  memory: "0"
              volumeMounts: []
            imagePullSecrets: []
            nodeSelector: {}
            volumes: []
    parameters: []
