---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/fluentd/src/main/fabric8/icon.png
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: fluentd
    version: 2.2.311
    group: io.fabric8.devops.apps
    kind: catalog
  name: catalog-fluentd
data:
  catalog-fluentd.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/fluentd/src/main/fabric8/icon.png"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "fluentd"
        version: "2.2.311"
        group: "io.fabric8.devops.apps"
      name: "fluentd"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "ServiceAccount"
      metadata:
        annotations: {}
        finalizers: []
        labels:
          provider: "fabric8"
          project: "fluentd"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "fluentd"
        ownerReferences: []
      imagePullSecrets: []
      secrets: []
    - apiVersion: "extensions/v1beta1"
      kind: "DaemonSet"
      metadata:
        annotations:
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/fluentd/src/main/fabric8/icon.png"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "fluentd"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "fluentd"
        ownerReferences: []
      spec:
        template:
          metadata:
            annotations:
              prometheus.io/scrape: "true"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "fluentd"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "ELASTICSEARCH_HOST"
                value: "elasticsearch"
              - name: "ELASTICSEARCH_PORT"
                value: "9200"
              image: "fabric8/fluentd-kubernetes:v1.19"
              name: "fluentd"
              ports:
              - containerPort: 24231
                name: "scrape"
              resources:
                limits:
                  cpu: "100m"
                requests: {}
              securityContext:
                privileged: true
              volumeMounts:
              - mountPath: "/var/log"
                name: "varlog"
              - mountPath: "/var/lib/docker/containers"
                name: "defaultdocker"
                readOnly: true
              - mountPath: "/mnt/ephemeral/docker/containers"
                name: "awsdocker"
                readOnly: true
              - mountPath: "/mnt/sda1/var/lib/docker/containers"
                name: "minikubedocker"
                readOnly: true
            imagePullSecrets: []
            nodeSelector: {}
            serviceAccountName: "fluentd"
            volumes:
            - hostPath:
                path: "/var/log"
              name: "varlog"
            - hostPath:
                path: "/var/lib/docker/containers"
              name: "defaultdocker"
            - hostPath:
                path: "/mnt/ephemeral/docker/containers"
              name: "awsdocker"
            - hostPath:
                path: "/mnt/sda1/var/lib/docker/containers"
              name: "minikubedocker"
    parameters: []
