---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: bad661f3285ecbcd6b7a9373e194bda075d832eb
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-forge/master/fabric8-forge/src/main/fabric8/icon.svg
    fabric8.io/git-branch: release-v2.3.88
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: fabric8-forge
    version: 2.3.88
    expose: "true"
    group: io.fabric8.forge.apps
    kind: catalog
  name: catalog-fabric8-forge
data:
  catalog-fabric8-forge.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "bad661f3285ecbcd6b7a9373e194bda075d832eb"
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-forge/master/fabric8-forge/src/main/fabric8/icon.svg"
        fabric8.io/git-branch: "release-v2.3.88"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "fabric8-forge"
        version: "2.3.88"
        expose: "true"
        group: "io.fabric8.forge.apps"
      name: "fabric8-forge"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-forge/master/fabric8-forge/src/main/fabric8/icon.svg"
          fabric8.io/git-commit: "bad661f3285ecbcd6b7a9373e194bda075d832eb"
          fabric8.io/git-branch: "release-v2.3.88"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "fabric8-forge"
          version: "2.3.88"
          group: "io.fabric8.forge.apps"
          expose: "true"
        name: "fabric8-forge"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - name: "http"
          port: 80
          protocol: "TCP"
          targetPort: 8080
        selector:
          project: "fabric8-forge"
          provider: "fabric8"
          group: "io.fabric8.forge.apps"
    - apiVersion: "v1"
      kind: "ConfigMap"
      metadata:
        annotations:
          fabric8.fabric8-forge/summary: "Fabric8 :: Forge"
          description: "Fabric8 :: Forge"
          fabric8.fabric8-forge/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-forge/master/fabric8-forge/src/main/fabric8/icon.svg"
          fabric8.io/yaml-schema: "type: object\nproperties:\n  jenkinsfile-library-git-repository:\n\
            \    type: string\n    description: The git clone URL for the library of Jenkinsfiles\
            \ used to associate CD pipelines with projects\n      reused across projects\n\
            \    default: https://github.com/fabric8io/jenkins-workflow-library.git\n\
            \  use-external-git-address:\n    type: boolean\n    description: Whether\
            \ we should use the external git URLs. Using internal tends to avoid DNS issues\
            \ of kubernetes pods not seeing external host names.\n  jenkins-gogs-user:\n\
            \    type: string\n    description: The user name for Jenkins to login to\
            \ Gogs\n    default: gogsadmin\n  jenkins-gogs-email:\n    type: string\n\
            \    description: The email address of the Jenkins user on Gogs\n    default:\
            \ 'gogsadmin@fabric8.local'\n  jenkins-gogs-password:\n    type: string\n\
            \    description: The password for Jenkins to login to Gogs\n    default:\
            \ RedHat$1\n  fabric8-default-environments:\n    type: string\n    description:\
            \ The list of default environment names to actual kubernetes namespaces\n\
            \    default: Testing=${namespace}-testing,Staging=${namespace}-staging,Production=${namespace}-prod\n"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "fabric8-forge"
          version: "2.3.88"
          group: "io.fabric8.forge.apps"
        name: "fabric8-forge"
        ownerReferences: []
      data:
        fabric8-default-environments: "Testing=${namespace}-testing,Staging=${namespace}-staging,Production=${namespace}-prod"
        jenkins-gogs-email: "gogsadmin@fabric8.local"
        jenkins-gogs-password: "RedHat$1"
        jenkins-gogs-user: "gogsadmin"
        jenkinsfile-library-git-repository: "https://github.com/fabric8io/fabric8-jenkinsfile-library.git"
        jenkinsfile-library-git-tag: "v2.2.311"
        use-external-git-address: "false"
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-forge/master/fabric8-forge/src/main/fabric8/icon.svg"
          fabric8.io/git-commit: "bad661f3285ecbcd6b7a9373e194bda075d832eb"
          fabric8.io/git-branch: "release-v2.3.88"
          fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=fabric8-forge&var-version=2.3.88"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "fabric8-forge"
          version: "2.3.88"
          group: "io.fabric8.forge.apps"
        name: "fabric8-forge"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            provider: "fabric8"
            project: "fabric8-forge"
            group: "io.fabric8.forge.apps"
        template:
          metadata:
            annotations:
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-forge/master/fabric8-forge/src/main/fabric8/icon.svg"
              fabric8.io/git-commit: "bad661f3285ecbcd6b7a9373e194bda075d832eb"
              fabric8.io/git-branch: "release-v2.3.88"
              fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=fabric8-forge&var-version=2.3.88"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "fabric8-forge"
              version: "2.3.88"
              group: "io.fabric8.forge.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "FABRIC8_DEFAULT_ENVIRONMENTS"
                valueFrom:
                  configMapKeyRef:
                    key: "fabric8-default-environments"
                    name: "fabric8-forge"
              - name: "JENKINSFILE_LIBRARY_GIT_REPOSITORY"
                valueFrom:
                  configMapKeyRef:
                    key: "jenkinsfile-library-git-repository"
                    name: "fabric8-forge"
              - name: "JENKINSFILE_LIBRARY_GIT_TAG"
                valueFrom:
                  configMapKeyRef:
                    key: "jenkinsfile-library-git-tag"
                    name: "fabric8-forge"
              - name: "USE_EXTERNAL_GIT_ADDRESS"
                valueFrom:
                  configMapKeyRef:
                    key: "use-external-git-address"
                    name: "fabric8-forge"
              - name: "KUBERNETES_TRUST_CERTIFICATES"
                value: "true"
              - name: "SKIP_TLS_VERIFY"
                value: "true"
              - name: "JENKINS_GOGS_PASSWORD"
                valueFrom:
                  configMapKeyRef:
                    key: "jenkins-gogs-password"
                    name: "fabric8-forge"
              - name: "JENKINS_GOGS_USER"
                valueFrom:
                  configMapKeyRef:
                    key: "jenkins-gogs-user"
                    name: "fabric8-forge"
              - name: "FABRIC8_ARCHETYPES_VERSION"
                value: "2.2.195"
              - name: "JAVA_OPTIONS"
                value: "-Dorg.apache.maven.log_transfer=true -Dorg.apache.cxf.logging.enabled=false"
              - name: "JENKINS_GOGS_EMAIL"
                valueFrom:
                  configMapKeyRef:
                    key: "jenkins-gogs-email"
                    name: "fabric8-forge"
              - name: "KUBERNETES_MASTER"
                value: "https://kubernetes.default.svc"
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              image: "fabric8/fabric8-forge:2.3.88"
              imagePullPolicy: "IfNotPresent"
              name: "fabric8-forge"
              ports:
              - containerPort: 8080
                name: "http"
                protocol: "TCP"
              - containerPort: 8778
                name: "jolokia"
                protocol: "TCP"
              readinessProbe:
                httpGet:
                  httpHeaders: []
                  path: "/_ping"
                  port: 8080
                initialDelaySeconds: 30
                timeoutSeconds: 10
              resources:
                limits:
                  cpu: "0"
                  memory: "0"
                requests:
                  cpu: "0"
                  memory: "0"
              securityContext:
                privileged: false
              volumeMounts: []
            imagePullSecrets: []
            nodeSelector: {}
            serviceAccountName: "fabric8"
            volumes: []
    parameters: []
