---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg
    fabric8.io/git-branch: release-v2.2.311
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: kibana
    version: 2.2.311
    expose: "true"
    group: io.fabric8.devops.apps
    kind: catalog
  name: catalog-kibana
data:
  catalog-kibana.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg"
        fabric8.io/git-branch: "release-v2.2.311"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "kibana"
        version: "2.2.311"
        expose: "true"
        group: "io.fabric8.devops.apps"
      name: "kibana"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/app-menu: "management"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          expose: "true"
          project: "kibana"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "kibana"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - name: "http"
          port: 80
          protocol: "TCP"
          targetPort: 5601
        selector:
          project: "kibana"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg"
          fabric8.io/git-branch: "release-v2.2.311"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=kibana&var-version=2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "kibana"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "kibana"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            project: "kibana"
            provider: "fabric8"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg"
              fabric8.io/git-branch: "release-v2.2.311"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=kibana&var-version=2.2.311"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "kibana"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "ELASTICSEARCH_URL"
                value: "http://elasticsearch:9200"
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              image: "fabric8/kibana4:v4.5.3"
              imagePullPolicy: "IfNotPresent"
              livenessProbe:
                initialDelaySeconds: 60
                tcpSocket:
                  port: 5601
              name: "kibana"
              ports: []
              readinessProbe:
                httpGet:
                  httpHeaders: []
                  path: "/"
                  port: 5601
                initialDelaySeconds: 5
              securityContext:
                privileged: false
              volumeMounts: []
            - args: []
              command: []
              env:
              - name: "ELASTICSEARCH_URL"
                value: "http://elasticsearch:9200"
              image: "fabric8/kibana-config:2.2.311"
              name: "logstash-template"
              ports: []
              volumeMounts: []
            imagePullSecrets: []
            nodeSelector: {}
            volumes: []
    parameters: []
