---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-irc/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.311
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: chat-irc
    version: target
    expose: "true"
    group: io.fabric8.devops.apps
    kind: catalog
  name: catalog-chat-irc
data:
  catalog-chat-irc.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-irc/src/main/fabric8/icon.png"
        fabric8.io/git-branch: "release-v2.2.311"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "chat-irc"
        version: "target"
        expose: "true"
        group: "io.fabric8.devops.apps"
      name: "chat-irc"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-irc/src/main/fabric8/icon.png"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "hubot-irc"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
          expose: "true"
        name: "hubot"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - port: 80
          protocol: "TCP"
          targetPort: 8080
        selector:
          project: "hubot-irc"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "hubot-notifier"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "hubot-notifier"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - name: "jolokia"
          port: 8778
          protocol: "TCP"
          targetPort: 8778
        selector:
          project: "hubot-notifier"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "ConfigMap"
      metadata:
        annotations:
          fabric8.hubot-irc/summary: "[Hubot](http://hubot.github.com) IRC chat bot"
          description: "Chat bot app using [Hubot](https://hubot.github.com/) and an IRC\
            \ server to communicate with fabric8."
          fabric8.hubot-irc/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-irc/src/main/fabric8/icon.png"
          fabric8.io/json-schema: "{\n  \"type\" : \"object\",\n  \"properties\" : {\n\
            \    \"HUBOT_IRC_USESSL\" : {\n      \"type\" : \"string\",\n      \"description\"\
            \ : \"Use SSL\",\n      \"default\" : \"1\"\n    },\n    \"HUBOT_GRAFANA_API_KEY\"\
            \ : {\n      \"type\" : \"string\",\n      \"description\" : \"API key for\
            \ a particular user\"\n    },\n    \"HUBOT_IRC_NICK\" : {\n      \"type\"\
            \ : \"string\",\n      \"description\" : \"The name that hubot should joing\
            \ the room as\",\n      \"default\" : \"fabric8\"\n    },\n    \"HUBOT_IRC_DEBUG\"\
            \ : {\n      \"type\" : \"string\",\n      \"description\" : \"Enables debug\
            \ logging\",\n      \"default\" : \"true\"\n    },\n    \"HUBOT_IRC_ROOMS\"\
            \ : {\n      \"type\" : \"string\",\n      \"description\" : \"List of rooms\
            \ to join including '#' prefix\",\n      \"default\" : \"#fabric8_default,#random\"\
            \n    },\n    \"HUBOT_GRAFANA_HOST\" : {\n      \"type\" : \"string\",\n \
            \     \"description\" : \"Host for your Grafana 2.0 install, e.g. 'http://play.grafana.org'\"\
            \n    },\n    \"HUBOT_IRC_UNFLOOD\" : {\n      \"type\" : \"string\",\n  \
            \    \"description\" : \"Unflood\",\n      \"default\" : \"false\"\n    },\n\
            \    \"HUBOT_JENKINS_URL\" : {\n      \"type\" : \"string\",\n      \"description\"\
            \ : \"The URL for the Jenkins CI server\",\n      \"default\" : \"http://jenkins\"\
            \n    },\n    \"HUBOT_IRC_SERVER\" : {\n      \"type\" : \"string\",\n   \
            \   \"description\" : \"The IRC server\",\n      \"default\" : \"irc.freenode.net\"\
            \n    },\n    \"HUBOT_IRC_NICKSERV_PASSWORD\" : {\n      \"type\" : \"string\"\
            ,\n      \"description\" : \"IRC nick password\"\n    },\n    \"HUBOT_IRC_PASSWORD\"\
            \ : {\n      \"type\" : \"string\",\n      \"description\" : \"IRC password\"\
            \n    }\n  }\n}"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "hubot-irc"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "hubot-irc"
        ownerReferences: []
      data:
        hubot-irc-server: "irc.freenode.net"
        hubot-irc-password: ""
        hubot-irc-unflood: "false"
        hubot-grafana-host: ""
        hubot-jenkins-url: "http://jenkins"
        hubot-irc-usessl: "1"
        hubot-irc-debug: "true"
        hubot-irc-nickserv-password: ""
        hubot-grafana-api-key: ""
        hubot-irc-rooms: "#fabric8_default,#random"
        hubot-irc-nick: "fabric8"
    - apiVersion: "v1"
      kind: "ConfigMap"
      metadata:
        annotations:
          fabric8.hubot-notifier/summary: "Watches the OpenShift environment and notifies\
            \ Hubot of events such as builds completing or failing"
          description: "Watches the OpenShift environment and notifies Hubot of events\
            \ such as builds completing or failing."
          fabric8.hubot-notifier/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png"
          fabric8.io/json-schema: "{\n  \"type\" : \"object\",\n  \"properties\" : {\n\
            \    \"HUBOT_USERNAME\" : {\n      \"type\" : \"string\",\n      \"description\"\
            \ : \"The username for Hubot to login to the chat service\",\n      \"default\"\
            \ : \"fabric8\"\n    },\n    \"KUBERNETES_DNS_DOMAIN\" : {\n      \"type\"\
            \ : \"string\",\n      \"description\" : \"The DNS domain added to the serviceName.namespace.svc.\
            \ to make the DNS name\",\n      \"default\" : \"cluster.local\"\n    },\n\
            \    \"HUBOT_PASSWORD\" : {\n      \"type\" : \"string\",\n      \"description\"\
            \ : \"The password for Hubot to login to the chat service\",\n      \"default\"\
            \ : \"RedHat$1\"\n    }\n  }\n}"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "hubot-notifier"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "hubot-notifier"
        ownerReferences: []
      data:
        hubot-password: "RedHat$1"
        kubernetes-dns-domain: "cluster.local"
        hubot-username: "fabric8"
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-irc/src/main/fabric8/icon.png"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/git-branch: "release-v2.2.311"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=hubot-irc&var-version=2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "hubot-irc"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "hubot-irc"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            provider: "fabric8"
            project: "hubot-irc"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-irc/src/main/fabric8/icon.png"
              fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
              fabric8.io/git-branch: "release-v2.2.311"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=hubot-irc&var-version=2.2.311"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "hubot-irc"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "HUBOT_IRC_USESSL"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-irc-usessl"
                    name: "hubot-irc"
              - name: "HUBOT_GRAFANA_API_KEY"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-grafana-api-key"
                    name: "hubot-irc"
              - name: "HUBOT_IRC_NICK"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-irc-nick"
                    name: "hubot-irc"
              - name: "HUBOT_IRC_DEBUG"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-irc-debug"
                    name: "hubot-irc"
              - name: "HUBOT_IRC_ROOMS"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-irc-rooms"
                    name: "hubot-irc"
              - name: "HUBOT_GRAFANA_HOST"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-grafana-host"
                    name: "hubot-irc"
              - name: "HUBOT_IRC_UNFLOOD"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-irc-unflood"
                    name: "hubot-irc"
              - name: "HUBOT_IRC_SERVER"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-irc-server"
                    name: "hubot-irc"
              - name: "HUBOT_JENKINS_URL"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-jenkins-url"
                    name: "hubot-irc"
              - name: "HUBOT_IRC_NICKSERV_PASSWORD"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-irc-nickserv-password"
                    name: "hubot-irc"
              - name: "HUBOT_IRC_PASSWORD"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-irc-password"
                    name: "hubot-irc"
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              image: "fabric8/hubot-irc:2.2.311"
              name: "hubot-irc"
              ports:
              - containerPort: 8080
                name: "http"
              resources:
                limits:
                  cpu: "0"
                  memory: "0"
                requests:
                  cpu: "0"
                  memory: "0"
              volumeMounts: []
            imagePullSecrets: []
            nodeSelector: {}
            volumes: []
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/git-branch: "release-v2.2.311"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=hubot-notifier&var-version=2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "hubot-notifier"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "hubot-notifier"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            provider: "fabric8"
            project: "hubot-notifier"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png"
              fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
              fabric8.io/git-branch: "release-v2.2.311"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=hubot-notifier&var-version=2.2.311"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "hubot-notifier"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "HUBOT_KUBERNETES_ROOM"
                value: "#fabric8_${namespace}"
              - name: "HUBOT_USERNAME"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-username"
                    name: "hubot-notifier"
              - name: "HUBOT_PASSWORD"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-password"
                    name: "hubot-notifier"
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              - name: "HUBOT_BUILD_ROOM"
                value: "#fabric8_${namespace}"
              image: "fabric8/hubot-notifier:2.2.311"
              imagePullPolicy: "IfNotPresent"
              name: "hubot-notifier"
              ports:
              - containerPort: 8778
                name: "jolokia"
              resources:
                limits:
                  cpu: "0"
                  memory: "0"
                requests:
                  cpu: "0"
                  memory: "0"
              securityContext:
                privileged: false
              volumeMounts: []
            imagePullSecrets: []
            nodeSelector: {}
            serviceAccountName: "fabric8"
            volumes: []
    parameters: []
