---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 0b90360981bed67ebde7b71cc6a96d34cca3dcc6
    fabric8.io/iconUrl: img/icons/activemq.svg
    fabric8.io/git-branch: release-v2.2.168
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: message-gateway
    version: 2.2.168
    group: io.fabric8.ipaas.apps
    kind: catalog
  name: catalog-message-gateway
data:
  catalog-message-gateway.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "0b90360981bed67ebde7b71cc6a96d34cca3dcc6"
        fabric8.io/iconUrl: "img/icons/activemq.svg"
        fabric8.io/git-branch: "release-v2.2.168"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "message-gateway"
        version: "2.2.168"
        group: "io.fabric8.ipaas.apps"
      name: "message-gateway"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/iconUrl: "img/icons/activemq.svg"
          fabric8.io/git-commit: "0b90360981bed67ebde7b71cc6a96d34cca3dcc6"
          fabric8.io/git-branch: "release-v2.2.168"
        finalizers: []
        labels:
          provider: "fabric8"
          group: "io.fabric8.ipaas.apps"
          project: "message-gateway"
          version: "2.2.168"
        name: "activemq"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - port: 61616
          protocol: "TCP"
          targetPort: 61616
        selector:
          provider: "fabric8"
          group: "io.fabric8.ipaas.apps"
          project: "message-gateway"
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/iconUrl: "img/icons/activemq.svg"
          fabric8.io/git-commit: "0b90360981bed67ebde7b71cc6a96d34cca3dcc6"
          fabric8.io/git-branch: "release-v2.2.168"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=message-gateway&var-version=2.2.168"
        finalizers: []
        labels:
          provider: "fabric8"
          group: "io.fabric8.ipaas.apps"
          project: "message-gateway"
          version: "2.2.168"
        name: "message-gateway"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            provider: "fabric8"
            group: "io.fabric8.ipaas.apps"
            project: "message-gateway"
        template:
          metadata:
            annotations:
              fabric8.io/iconUrl: "img/icons/activemq.svg"
              fabric8.io/git-commit: "0b90360981bed67ebde7b71cc6a96d34cca3dcc6"
              fabric8.io/git-branch: "release-v2.2.168"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=message-gateway&var-version=2.2.168"
            finalizers: []
            labels:
              provider: "fabric8"
              group: "io.fabric8.ipaas.apps"
              project: "message-gateway"
              version: "2.2.168"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              image: "fabric8/message-gateway:2.2.168"
              imagePullPolicy: "IfNotPresent"
              name: "message-gateway"
              ports:
              - containerPort: 61616
                name: "amq"
              - containerPort: 8778
                name: "jolokia"
              resources:
                limits:
                  cpu: "0"
                  memory: "0"
                requests:
                  cpu: "0"
                  memory: "0"
              securityContext:
                privileged: false
              volumeMounts: []
            imagePullSecrets: []
            nodeSelector: {}
            volumes: []
    parameters: []
