---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-node-exporter/src/main/fabric8/icon.png
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: prometheus-node-exporter
    version: 2.2.311
    group: io.fabric8.devops.apps
    kind: catalog
  name: catalog-prometheus-node-exporter
data:
  catalog-prometheus-node-exporter.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-node-exporter/src/main/fabric8/icon.png"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "prometheus-node-exporter"
        version: "2.2.311"
        group: "io.fabric8.devops.apps"
      name: "prometheus-node-exporter"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "ServiceAccount"
      metadata:
        annotations: {}
        finalizers: []
        labels:
          provider: "fabric8"
          project: "prometheus-node-exporter"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "node-exporter"
        ownerReferences: []
      imagePullSecrets: []
      secrets: []
    - apiVersion: "extensions/v1beta1"
      kind: "DaemonSet"
      metadata:
        annotations:
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-node-exporter/src/main/fabric8/icon.png"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "prometheus-node-exporter"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "node-exporter"
        ownerReferences: []
      spec:
        template:
          metadata:
            annotations: {}
            finalizers: []
            labels:
              provider: "fabric8"
              project: "prometheus-node-exporter"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            name: "node-exporter"
            ownerReferences: []
          spec:
            containers:
            - args:
              - "-collector.procfs"
              - "/host/proc"
              - "-collector.sysfs"
              - "/host/proc"
              - "-collector.filesystem.ignored-mount-points"
              - "^/(sys|proc|dev|host|etc)($|/)"
              command: []
              env: []
              image: "prom/node-exporter"
              name: "node-exporter"
              ports:
              - containerPort: 9100
                name: "scrape"
              volumeMounts:
              - mountPath: "/host/proc"
                name: "host-proc"
                readOnly: true
              - mountPath: "/host/sys"
                name: "host-sys"
                readOnly: true
              - mountPath: "/rootfs"
                name: "host-root"
                readOnly: true
            hostNetwork: true
            imagePullSecrets: []
            nodeSelector: {}
            serviceAccountName: "node-exporter"
            volumes:
            - hostPath:
                path: "/proc"
              name: "host-proc"
            - hostPath:
                path: "/sys"
              name: "host-sys"
            - hostPath:
                path: "/"
              name: "host-root"
    parameters: []
