---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 0b90360981bed67ebde7b71cc6a96d34cca3dcc6
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.168
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: zookeeper
    version: 2.2.168
    expose: "true"
    serverId: "1"
    group: io.fabric8.ipaas.apps
    kind: catalog
  name: catalog-zookeeper
data:
  catalog-zookeeper.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "0b90360981bed67ebde7b71cc6a96d34cca3dcc6"
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png"
        fabric8.io/git-branch: "release-v2.2.168"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "zookeeper"
        version: "2.2.168"
        expose: "true"
        serverId: "1"
        group: "io.fabric8.ipaas.apps"
      name: "zookeeper"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png"
          fabric8.io/git-commit: "0b90360981bed67ebde7b71cc6a96d34cca3dcc6"
          fabric8.io/git-branch: "release-v2.2.168"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "zookeeper"
          version: "2.2.168"
          group: "io.fabric8.ipaas.apps"
          expose: "true"
        name: "zookeeper"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - name: "client"
          port: 2181
          targetPort: 2181
        selector:
          project: "zookeeper"
          provider: "fabric8"
          group: "io.fabric8.ipaas.apps"
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png"
          fabric8.io/git-commit: "0b90360981bed67ebde7b71cc6a96d34cca3dcc6"
          fabric8.io/git-branch: "release-v2.2.168"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=zookeeper&var-version=2.2.168"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "zookeeper"
          version: "2.2.168"
          group: "io.fabric8.ipaas.apps"
          serverId: "1"
        name: "zookeeper"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            provider: "fabric8"
            project: "zookeeper"
            group: "io.fabric8.ipaas.apps"
        template:
          metadata:
            annotations:
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png"
              fabric8.io/git-commit: "0b90360981bed67ebde7b71cc6a96d34cca3dcc6"
              fabric8.io/git-branch: "release-v2.2.168"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=zookeeper&var-version=2.2.168"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "zookeeper"
              version: "2.2.168"
              group: "io.fabric8.ipaas.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "ENSEMBLE_SIZE"
                value: "1"
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              image: "fabric8/zookeeper:2.2.168"
              imagePullPolicy: "IfNotPresent"
              name: "zookeeper"
              ports:
              - containerPort: 2181
                name: "zkclient"
              - containerPort: 8778
                name: "jolokia"
              resources:
                limits:
                  cpu: "0"
                  memory: "0"
                requests:
                  cpu: "0"
                  memory: "0"
              securityContext:
                privileged: false
              volumeMounts:
              - mountPath: "/opt/zookeeper/data"
                name: "data"
                readOnly: false
              - mountPath: "/opt/zookeeper/log"
                name: "log"
                readOnly: false
            imagePullSecrets: []
            nodeSelector: {}
            volumes:
            - emptyDir:
                medium: "Memory"
              name: "data"
            - emptyDir:
                medium: "Memory"
              name: "log"
    parameters: []
