---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    provider: fabric8
    project: exposecontroller
    version: 2.2.311
    group: io.fabric8.devops.apps
  name: exposecontroller
data:
  config.yml: |
    domain:
    exposer:
