---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    description: Defines the environments used by your Continuous Delivery pipelines.
    fabric8.console/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-console/master/app-kubernetes/src/main/fabric8/icon.svg
  labels:
    kind: environments
    provider: fabric8
    project: fabric8-console
    version: 2.2.199
    group: io.fabric8.platform.console
  name: fabric8-environments
