---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    provider: fabric8
    project: gogs
    version: 2.2.311
    group: io.fabric8.devops.apps
  name: fabric8-git-app-secrets
  namespace: user-secrets-source-admin
data:
  gogs: default-git-gogs
