---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.gogs/summary: '[Gogs](http://gogs/) - A self-hosted Git service written
      in Go'
    description: |
      Gogs is a self-hosted Git service written in Go.

      More details on the <a href="http://gogs.io/" target="gogs">Gogs home page</a>.
    fabric8.gogs/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
    expose.config.fabric8.io/url-key: gogs-server--root-url
    expose.config.fabric8.io/oauth-authorize-url-key: oauth-authorize-uri
    fabric8.io/json-schema: |-
      {
        "type" : "object",
        "properties" : {
          "GOGS_SERVER__ROOT_URL" : {
            "type" : "string",
            "description" : "The root URL for the gogs server"
          },
          "DOMAIN" : {
            "type" : "string",
            "description" : "The domain name applications are installed on",
            "default" : "vagrant.f8"
          },
          "ADMIN_USER_EMAIL" : {
            "type" : "string",
            "description" : "The email address of the admin user on Gogs",
            "default" : "gogsadmin@fabric8.local"
          },
          "ADMIN_USER_PASSWORD" : {
            "type" : "string",
            "description" : "The password to login to Gogs",
            "default" : "RedHat$1"
          },
          "GOGS_SERVER__PROTOCOL" : {
            "type" : "string",
            "description" : "The protocol for gogs to use; either http or https",
            "default" : "http"
          },
          "GOGS_OAUTH_OPENSHIFT__ENABLED" : {
            "type" : "string",
            "default" : "true"
          },
          "ADMIN_USER_CREATE" : {
            "type" : "string",
            "description" : "Should we create an admin user on startup",
            "default" : "true"
          },
          "GOGS_OAUTH_OPENSHIFT__TOKEN_URL" : {
            "type" : "string"
          },
          "GOGS_OAUTH_OPENSHIFT__SCOPES" : {
            "type" : "string"
          },
          "GOGS_OAUTH_OPENSHIFT__AUTH_URL" : {
            "type" : "string"
          },
          "GOGS_WEBHOOK__TASK_INTERVAL" : {
            "type" : "string",
            "default" : "true"
          },
          "GOGS_WEBHOOK__SKIP_TLS_VERIFY" : {
            "type" : "string",
            "default" : "true"
          },
          "GOGS_SERVER__DOMAIN" : {
            "type" : "string",
            "description" : "The gogs server name",
            "default" : "gogs.vagrant.f8"
          },
          "ADMIN_USER_NAME" : {
            "type" : "string",
            "description" : "The user name to login to Gogs",
            "default" : "gogsadmin"
          },
          "GOGS_OAUTH__ENABLED" : {
            "type" : "string",
            "default" : "true"
          },
          "GOGS_OAUTH_TWITTER__ENABLED" : {
            "type" : "string",
            "default" : "false"
          },
          "KUBERNETES_ADMIN_USER" : {
            "type" : "string",
            "description" : "The default Kubernetes admin user",
            "default" : "admin"
          },
          "GOGS_OAUTH_OPENSHIFT__CLIENT_ID" : {
            "type" : "string",
            "default" : "gogs"
          }
        }
      }
  labels:
    provider: fabric8
    project: gogs
    version: 2.2.311
    group: io.fabric8.devops.apps
  name: gogs
data:
  admin-user-create: "true"
  admin-user-email: gogsadmin@fabric8.local
  admin-user-name: gogsadmin
  admin-user-password: RedHat$1
  gogs-oauth--enabled: "true"
  gogs-oauth-openshift--auth-url: ""
  gogs-oauth-openshift--client-id: gogs
  gogs-oauth-openshift--enabled: "true"
  gogs-oauth-openshift--scopes: ""
  gogs-oauth-openshift--token-url: ""
  gogs-oauth-twitter--enabled: "false"
  gogs-server--root-url: ""
  gogs-webhook--skip-tls-verify: "true"
  gogs-webhook--task-interval: "true"
  kubernetes-admin-user: admin
