---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/nexus/src/main/fabric8/icon.png
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/git-branch: release-v2.2.311
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=nexus&var-version=2.2.311
  labels:
    provider: fabric8
    project: nexus
    version: 2.2.311
    group: io.fabric8.devops.apps
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: fabric8
      project: nexus
      group: io.fabric8.devops.apps
  template:
    metadata:
      annotations:
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/nexus/src/main/fabric8/icon.png
        fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
        fabric8.io/git-branch: release-v2.2.311
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=nexus&var-version=2.2.311
        pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"init","command":["chmod","777","/sonatype-work/storage"],"volumeMounts":[{"mountPath":"/sonatype-work/storage","name":"nexus-storage"}]}]'
      labels:
        provider: fabric8
        project: nexus
        version: 2.2.311
        group: io.fabric8.devops.apps
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: fabric8/nexus:2.2.311
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /content/repositories/
            port: 8081
          initialDelaySeconds: 180
          timeoutSeconds: 10
        name: nexus
        ports:
        - containerPort: 8081
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /content/repositories/
            port: 8081
          initialDelaySeconds: 60
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        volumeMounts:
        - mountPath: /sonatype-work/storage
          name: nexus-storage
          readOnly: false
      volumes:
      - name: nexus-storage
        persistentVolumeClaim:
          claimName: nexus-storage
