apiVersion: v1
appVersion: 1.6.0
description: A Helm chart for tensorflow notebook and tensorboard
home: https://www.tensorflow.org
maintainers:
- email: cheyang@163.com
  name: cheyang
name: tensorflow-notebook
sources:
- https://github.com/tensorflow/tensorflow
- https://github.com/jupyter
version: 0.1.2
